version: "3.9"
services:
  eta_pricing:
    build: .
    image: autofleet-eta:latest
    command: uvicorn api.eta_service_pricing:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  maintenance:
    build: .
    image: autofleet-maint:latest
    command: uvicorn api.maintenance_service:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
  nlp:
    build: .
    image: autofleet-nlp:latest
    command: uvicorn api.nlp_service:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
